### ISSUE TITLE
Macro does not work on languages other than English

### ISSUE THREAD

**Issue by tildejustin** [pjagada/spawn-juicer#3]
In testing on 1.16.5, all 5 versions of normal English work, but upside down, shakespearean, lolcat, and japanese do not work. My guess as to the problem would be the script is parsing logs and it can't find what it's looking for because it's renamed, but I really have no clue. The instance resets until it finds a seed but just stays open and never fullscreens, and when you try to reset on an instance with an unsupported language it gives the error "Could not find option in options.txt." and closes the macro.

**Comment by pjagada** [comment]
I will not be adding support for other languages since there are too many languages for me to add support for all of them. If you want to make a pull request and add support for whatever languages you would like, that's fine.
